[project]
name = 'Blockchain-Based-Quality-Assurance-Continuous-Monitoring-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.quality-monitor-verification]
path = 'contracts/quality-monitor-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
